// CodeGear C++Builder
// Copyright (c) 1995, 2009 by Embarcadero Technologies, Inc.
// All rights reserved

// (DO NOT EDIT: machine generated header) 'Sbconstants.pas' rev: 21.00

#ifndef SbconstantsHPP
#define SbconstantsHPP

#pragma delphiheader begin
#pragma option push
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member functions
#pragma pack(push,8)
#include <System.hpp>	// Pascal unit
#include <Sysinit.hpp>	// Pascal unit
#include <Sbtypes.hpp>	// Pascal unit

//-- user supplied -----------------------------------------------------------

namespace Sbconstants
{
//-- type declarations -------------------------------------------------------
typedef StaticArray<System::UnicodeString, 2> Sbconstants__1;

typedef Sbtypes::ByteArray TByteArrayConst;

//-- var, const, procedure ---------------------------------------------------
extern PACKAGE StaticArray<System::WideChar, 64> EncArr;
#define CRLFStr L"\r\n"
static const WideChar CRStr = (WideChar)(0xd);
static const WideChar LFStr = (WideChar)(0xa);
#define LFLFStr L"\n\n"
#define CRLFCRLFStr L"\r\n\r\n"
#define CRLFCRLFZeroStr L"\r\n\r\n\u0000"
#define CRLFTABStr L"\r\n\t"
#define CRLFSPACEStr L"\r\n "
#define TwoDashesStr L"--"
static const WideChar SpaceStr = (WideChar)(0x20);
static const WideChar EqualCharStr = (WideChar)(0x3d);
static const ShortInt TabByte = 0x9;
static const ShortInt CRByte = 0xd;
static const ShortInt LFByte = 0xa;
static const ShortInt SpaceByte = 0x20;
static const ShortInt DoubleQuoteByte = 0x22;
static const ShortInt ColonByte = 0x3a;
static const ShortInt BackslashByte = 0x5c;
extern PACKAGE StaticArray<System::WideChar, 16> HexChars;
extern PACKAGE Sbconstants__1 BooleanStrings;
static const int SecondsInDay = 0x15180;
static const Word SecondsInHour = 0xe10;
static const ShortInt SecondsInMinute = 0x3c;
static const ShortInt HoursInDay = 0x18;
static const ShortInt MinutesInHour = 0x3c;
static const Word MinutesInDay = 0x5a0;
static const ShortInt AnsiStrStartOffset = 0x1;
static const ShortInt AnsiStrStartInvOffset = 0x0;
static const ShortInt StringStartOffset = 0x1;
static const ShortInt StringStartInvOffset = 0x0;
static const WideChar cSBPathSeparator = (WideChar)(0x5c);
static const int SB_CERT_ALGORITHM_ID_RSA_ENCRYPTION = 0;
static const int SB_CERT_ALGORITHM_MD2_RSA_ENCRYPTION = 1;
static const int SB_CERT_ALGORITHM_MD5_RSA_ENCRYPTION = 2;
static const int SB_CERT_ALGORITHM_SHA1_RSA_ENCRYPTION = 3;
static const int SB_CERT_ALGORITHM_ID_DSA = 4;
static const int SB_CERT_ALGORITHM_ID_DSA_SHA1 = 5;
static const int SB_CERT_ALGORITHM_DH_PUBLIC = 6;
static const int SB_CERT_ALGORITHM_SHA224_RSA_ENCRYPTION = 7;
static const int SB_CERT_ALGORITHM_SHA256_RSA_ENCRYPTION = 8;
static const int SB_CERT_ALGORITHM_SHA384_RSA_ENCRYPTION = 9;
static const int SB_CERT_ALGORITHM_SHA512_RSA_ENCRYPTION = 10;
static const int SB_CERT_ALGORITHM_ID_RSAPSS = 11;
static const int SB_CERT_ALGORITHM_ID_RSAOAEP = 12;
static const int SB_CERT_ALGORITHM_RSASIGNATURE_RIPEMD160 = 13;
static const int SB_CERT_ALGORITHM_ID_ELGAMAL = 14;
static const int SB_CERT_ALGORITHM_SHA1_ECDSA = 15;
static const int SB_CERT_ALGORITHM_RECOMMENDED_ECDSA = 16;
static const int SB_CERT_ALGORITHM_SHA224_ECDSA = 17;
static const int SB_CERT_ALGORITHM_SHA256_ECDSA = 18;
static const int SB_CERT_ALGORITHM_SHA384_ECDSA = 19;
static const int SB_CERT_ALGORITHM_SHA512_ECDSA = 20;
static const int SB_CERT_ALGORITHM_EC = 21;
static const int SB_CERT_ALGORITHM_SPECIFIED_ECDSA = 22;
static const int SB_CERT_ALGORITHM_GOST_R3410_1994 = 23;
static const int SB_CERT_ALGORITHM_GOST_R3410_2001 = 24;
static const int SB_CERT_ALGORITHM_GOST_R3411_WITH_R3410_1994 = 25;
static const int SB_CERT_ALGORITHM_GOST_R3411_WITH_R3410_2001 = 26;
static const int SB_CERT_ALGORITHM_SHA1_ECDSA_PLAIN = 27;
static const int SB_CERT_ALGORITHM_SHA224_ECDSA_PLAIN = 28;
static const int SB_CERT_ALGORITHM_SHA256_ECDSA_PLAIN = 29;
static const int SB_CERT_ALGORITHM_SHA384_ECDSA_PLAIN = 30;
static const int SB_CERT_ALGORITHM_SHA512_ECDSA_PLAIN = 31;
static const int SB_CERT_ALGORITHM_RIPEMD160_ECDSA_PLAIN = 32;
static const int SB_CERT_ALGORITHM_WHIRLPOOL_RSA_ENCRYPTION = 33;
static const int SB_CERT_MGF1 = 513;
static const int SB_CERT_MGF1_SHA1 = 514;
static const int SB_CERT_MGF1_SHA224 = 515;
static const int SB_CERT_MGF1_SHA256 = 516;
static const int SB_CERT_MGF1_SHA384 = 517;
static const int SB_CERT_MGF1_SHA512 = 518;
static const int SB_CERT_MGF1_RIPEMD160 = 519;
static const int SB_CERT_MGF1_WHIRLPOOL = 520;
static const int SB_CERT_ALGORITHM_UNKNOWN = 65535;
extern PACKAGE Sbtypes::ByteArray SB_OID_RC4;
extern PACKAGE Sbtypes::ByteArray SB_OID_RSAENCRYPTION;
extern PACKAGE Sbtypes::ByteArray SB_OID_EA_RSA;
extern PACKAGE Sbtypes::ByteArray SB_OID_RSAPSS;
extern PACKAGE Sbtypes::ByteArray SB_OID_RSAOAEP;
extern PACKAGE Sbtypes::ByteArray SB_OID_DSA;
extern PACKAGE Sbtypes::ByteArray SB_OID_DSA_SHA1;
extern PACKAGE Sbtypes::ByteArray SB_OID_DSA_SHA224;
extern PACKAGE Sbtypes::ByteArray SB_OID_DSA_SHA256;
extern PACKAGE Sbtypes::ByteArray SB_OID_DSA_ALT;
extern PACKAGE Sbtypes::ByteArray SB_OID_DSA_SHA1_ALT;
extern PACKAGE Sbtypes::ByteArray SB_OID_DH;
extern PACKAGE Sbtypes::ByteArray SB_OID_DES_EDE3_CBC;
extern PACKAGE Sbtypes::ByteArray SB_OID_PKCS7_DATA;
extern PACKAGE Sbtypes::ByteArray SB_OID_RC2_CBC;
extern PACKAGE Sbtypes::ByteArray SB_OID_DES_CBC;
extern PACKAGE Sbtypes::ByteArray SB_OID_SHA1_RSAENCRYPTION;
extern PACKAGE Sbtypes::ByteArray SB_OID_SHA1_RSAENCRYPTION2;
extern PACKAGE Sbtypes::ByteArray SB_OID_SHA224_RSAENCRYPTION;
extern PACKAGE Sbtypes::ByteArray SB_OID_SHA256_RSAENCRYPTION;
extern PACKAGE Sbtypes::ByteArray SB_OID_SHA384_RSAENCRYPTION;
extern PACKAGE Sbtypes::ByteArray SB_OID_SHA512_RSAENCRYPTION;
extern PACKAGE Sbtypes::ByteArray SB_OID_RSASIGNATURE_RIPEMD160;
extern PACKAGE Sbtypes::ByteArray SB_OID_TSTINFO;
extern PACKAGE Sbtypes::ByteArray SB_OID_AES128_CBC;
extern PACKAGE Sbtypes::ByteArray SB_OID_AES192_CBC;
extern PACKAGE Sbtypes::ByteArray SB_OID_AES256_CBC;
extern PACKAGE Sbtypes::ByteArray SB_OID_SERPENT128_CBC;
extern PACKAGE Sbtypes::ByteArray SB_OID_SERPENT192_CBC;
extern PACKAGE Sbtypes::ByteArray SB_OID_SERPENT256_CBC;
extern PACKAGE Sbtypes::ByteArray SB_OID_CAST5_CBC;
extern PACKAGE Sbtypes::ByteArray SB_OID_BLOWFISH_CBC;
extern PACKAGE Sbtypes::ByteArray SB_OID_CAMELLIA128_CBC;
extern PACKAGE Sbtypes::ByteArray SB_OID_CAMELLIA192_CBC;
extern PACKAGE Sbtypes::ByteArray SB_OID_CAMELLIA256_CBC;
extern PACKAGE Sbtypes::ByteArray SB_OID_SEED;
extern PACKAGE Sbtypes::ByteArray SB_OID_RABBIT;
extern PACKAGE Sbtypes::ByteArray SB_OID_IDENTITY;
extern PACKAGE Sbtypes::ByteArray SB_OID_IDENTITY_ELDOS;
extern PACKAGE Sbtypes::ByteArray SB_OID_TWOFISH128_ELDOS;
extern PACKAGE Sbtypes::ByteArray SB_OID_TWOFISH256_ELDOS;
extern PACKAGE Sbtypes::ByteArray SB_OID_TWOFISH192_ELDOS;
extern PACKAGE Sbtypes::ByteArray SB_OID_RSASIGNATURE_RIPEMD160_ISO9796;
extern PACKAGE Sbtypes::ByteArray SB_OID_WHIRLPOOL_RSAENCRYPTION_ELDOS;
extern PACKAGE Sbtypes::ByteArray SB_OID_MGF1;
extern PACKAGE Sbtypes::ByteArray SB_OID_MGF1_SHA1;
extern PACKAGE Sbtypes::ByteArray SB_OID_MGF1_SHA224;
extern PACKAGE Sbtypes::ByteArray SB_OID_MGF1_SHA256;
extern PACKAGE Sbtypes::ByteArray SB_OID_MGF1_SHA384;
extern PACKAGE Sbtypes::ByteArray SB_OID_MGF1_SHA512;
extern PACKAGE Sbtypes::ByteArray SB_OID_MGF1_RIPEMD160;
extern PACKAGE Sbtypes::ByteArray SB_OID_MGF1_WHIRLPOOL;
extern PACKAGE Sbtypes::ByteArray SB_OID_OAEP_SRC_SPECIFIED;
extern PACKAGE Sbtypes::ByteArray SB_OID_PBE_MD2_DES;
extern PACKAGE Sbtypes::ByteArray SB_OID_PBE_MD2_RC2;
extern PACKAGE Sbtypes::ByteArray SB_OID_PBE_MD5_DES;
extern PACKAGE Sbtypes::ByteArray SB_OID_PBE_MD5_RC2;
extern PACKAGE Sbtypes::ByteArray SB_OID_PBE_SHA1_DES;
extern PACKAGE Sbtypes::ByteArray SB_OID_PBE_SHA1_RC2;
extern PACKAGE Sbtypes::ByteArray SB_OID_PBES2;
extern PACKAGE Sbtypes::ByteArray SB_OID_PBKDF2;
extern PACKAGE Sbtypes::ByteArray SB_OID_PBMAC1;
extern PACKAGE Sbtypes::ByteArray SB_OID_PBE_SHA1_RC4_128;
extern PACKAGE Sbtypes::ByteArray SB_OID_PBE_SHA1_RC4_40;
extern PACKAGE Sbtypes::ByteArray SB_OID_PBE_SHA1_3DES;
extern PACKAGE Sbtypes::ByteArray SB_OID_PBE_SHA1_RC2_128;
extern PACKAGE Sbtypes::ByteArray SB_OID_PBE_SHA1_RC2_40;
extern PACKAGE Sbtypes::ByteArray SB_OID_MD2_RSAENCRYPTION;
extern PACKAGE Sbtypes::ByteArray SB_OID_MD4_RSAENCRYPTION;
extern PACKAGE Sbtypes::ByteArray SB_OID_MD5_RSAENCRYPTION;
extern PACKAGE Sbtypes::ByteArray SB_OID_SHA1_RSA;
extern PACKAGE Sbtypes::ByteArray SB_OID_SHA1_DSA;
extern PACKAGE Sbtypes::ByteArray SB_OID_PKCS15;
extern PACKAGE Sbtypes::ByteArray SB_OID_PWRI_KEK;
extern PACKAGE Sbtypes::ByteArray SB_OID_DATA;
extern PACKAGE Sbtypes::ByteArray SB_OID_MD2;
extern PACKAGE Sbtypes::ByteArray SB_OID_MD4;
extern PACKAGE Sbtypes::ByteArray SB_OID_MD5;
extern PACKAGE Sbtypes::ByteArray SB_OID_SHA1;
extern PACKAGE Sbtypes::ByteArray SB_OID_SHA224;
extern PACKAGE Sbtypes::ByteArray SB_OID_SHA256;
extern PACKAGE Sbtypes::ByteArray SB_OID_SHA384;
extern PACKAGE Sbtypes::ByteArray SB_OID_SHA512;
extern PACKAGE Sbtypes::ByteArray SB_OID_RIPEMD160;
extern PACKAGE Sbtypes::ByteArray SB_OID_SSL3;
extern PACKAGE Sbtypes::ByteArray SB_OID_WHIRLPOOL;
extern PACKAGE Sbtypes::ByteArray SB_OID_HMACSHA1;
extern PACKAGE Sbtypes::ByteArray SB_OID_HMACSHA1_PKCS;
extern PACKAGE Sbtypes::ByteArray SB_OID_HMACSHA224;
extern PACKAGE Sbtypes::ByteArray SB_OID_HMACSHA256;
extern PACKAGE Sbtypes::ByteArray SB_OID_HMACSHA384;
extern PACKAGE Sbtypes::ByteArray SB_OID_HMACSHA512;
extern PACKAGE Sbtypes::ByteArray SB_OID_RSA_HMACSHA1;
extern PACKAGE Sbtypes::ByteArray SB_OID_UMAC32;
extern PACKAGE Sbtypes::ByteArray SB_OID_UMAC64;
extern PACKAGE Sbtypes::ByteArray SB_OID_UMAC96;
extern PACKAGE Sbtypes::ByteArray SB_OID_UMAC128;
extern PACKAGE Sbtypes::ByteArray SB_OID_CONTENT_TYPE;
extern PACKAGE Sbtypes::ByteArray SB_OID_MESSAGE_DIGEST;
extern PACKAGE Sbtypes::ByteArray SB_OID_SIGNING_TIME;
extern PACKAGE Sbtypes::ByteArray SB_OID_COUNTER_SIGNATURE;
extern PACKAGE Sbtypes::ByteArray SB_OID_SMIME_CAPABILITIES;
extern PACKAGE Sbtypes::ByteArray SB_OID_TIMESTAMP_TOKEN;
extern PACKAGE Sbtypes::ByteArray SB_OID_SIGNING_CERTIFICATE;
extern PACKAGE Sbtypes::ByteArray SB_OID_SIGNING_CERTIFICATEV2;
extern PACKAGE Sbtypes::ByteArray SB_OID_CONTENT_HINTS;
extern PACKAGE Sbtypes::ByteArray SB_OID_CONTENT_IDENTIFIER;
extern PACKAGE Sbtypes::ByteArray SB_OID_CONTENT_REFERENCE;
extern PACKAGE Sbtypes::ByteArray SB_OID_SIGNATURE_POLICY;
extern PACKAGE Sbtypes::ByteArray SB_OID_COMMITMENT_TYPE;
extern PACKAGE Sbtypes::ByteArray SB_OID_SIGNER_LOCATION;
extern PACKAGE Sbtypes::ByteArray SB_OID_SIGNER_ATTRIBUTES;
extern PACKAGE Sbtypes::ByteArray SB_OID_CONTENT_TIMESTAMP;
extern PACKAGE Sbtypes::ByteArray SB_OID_CERTIFICATE_REFS;
extern PACKAGE Sbtypes::ByteArray SB_OID_REVOCATION_REFS;
extern PACKAGE Sbtypes::ByteArray SB_OID_CERTIFICATE_VALUES;
extern PACKAGE Sbtypes::ByteArray SB_OID_REVOCATION_VALUES;
extern PACKAGE Sbtypes::ByteArray SB_OID_ESCTIMESTAMP;
extern PACKAGE Sbtypes::ByteArray SB_OID_CERTCRLTIMESTAMP;
extern PACKAGE Sbtypes::ByteArray SB_OID_ARCHIVETIMESTAMP;
extern PACKAGE Sbtypes::ByteArray SB_OID_ARCHIVETIMESTAMP2;
extern PACKAGE Sbtypes::ByteArray SB_OID_ARCHIVETIMESTAMP3;
extern PACKAGE Sbtypes::ByteArray SB_OID_ATSHASHINDEX;
extern PACKAGE Sbtypes::ByteArray SB_OID_SPC_INDIRECT_DATA;
extern PACKAGE Sbtypes::ByteArray SB_OID_SPC_SP_AGENCY_INFO;
extern PACKAGE Sbtypes::ByteArray SB_OID_SPC_STATEMENT_TYPE_OBJID;
extern PACKAGE Sbtypes::ByteArray SB_OID_SPC_STATEMENT_TYPE;
extern PACKAGE Sbtypes::ByteArray SB_OID_SPC_SP_OPUS_INFO;
extern PACKAGE Sbtypes::ByteArray SB_OID_SPC_PE_IMAGE_DATA;
extern PACKAGE Sbtypes::ByteArray SB_OID_SPC_MINIMAL_CRITERIA;
extern PACKAGE Sbtypes::ByteArray SB_OID_SPC_FINANCIAL_CRITERIA;
extern PACKAGE Sbtypes::ByteArray SB_OID_SPC_LINK;
extern PACKAGE Sbtypes::ByteArray SB_OID_SPC_HASH_INFO;
extern PACKAGE Sbtypes::ByteArray SB_OID_SPC_SIPINFO;
extern PACKAGE Sbtypes::ByteArray SB_OID_SPC_CERT_EXTENSIONS;
extern PACKAGE Sbtypes::ByteArray SB_OID_SPC_RAW_FILE_DATA;
extern PACKAGE Sbtypes::ByteArray SB_OID_SPC_STRUCTURED_STORAGE_DATA;
extern PACKAGE Sbtypes::ByteArray SB_OID_SPC_JAVA_CLASS_DATA;
extern PACKAGE Sbtypes::ByteArray SB_OID_SPC_INDIVIDUAL_SP_KEY_PURPOSE;
extern PACKAGE Sbtypes::ByteArray SB_OID_SPC_COMMERCIAL_SP_KEY_PURPOSE;
extern PACKAGE Sbtypes::ByteArray SB_OID_SPC_CAB_DATA;
extern PACKAGE Sbtypes::ByteArray SB_OID_QT_CPS;
extern PACKAGE Sbtypes::ByteArray SB_OID_QT_UNOTICE;
extern PACKAGE Sbtypes::ByteArray SB_OID_SERVER_AUTH;
extern PACKAGE Sbtypes::ByteArray SB_OID_CLIENT_AUTH;
extern PACKAGE Sbtypes::ByteArray SB_OID_CODE_SIGNING;
extern PACKAGE Sbtypes::ByteArray SB_OID_EMAIL_PROT;
extern PACKAGE Sbtypes::ByteArray SB_OID_TIME_STAMPING;
extern PACKAGE Sbtypes::ByteArray SB_OID_OCSP_SIGNING;
extern PACKAGE Sbtypes::ByteArray SB_OID_ACCESS_METHOD_OCSP;
extern PACKAGE Sbtypes::ByteArray SB_OID_ACCESS_METHOD_CAISSUER;
extern PACKAGE Sbtypes::ByteArray SB_OID_UNSTRUCTURED_NAME;
extern PACKAGE Sbtypes::ByteArray SB_OID_CERT_EXTENSIONS;
extern PACKAGE Sbtypes::ByteArray SB_OID_CERT_EXTENSIONS_MS;
extern PACKAGE Sbtypes::ByteArray SB_OID_GOST_28147_1989;
extern PACKAGE Sbtypes::ByteArray SB_OID_GOST_28147_1989_MAC;
extern PACKAGE Sbtypes::ByteArray SB_OID_GOST_R3410_2001;
extern PACKAGE Sbtypes::ByteArray SB_OID_GOST_R3410_1994;
extern PACKAGE Sbtypes::ByteArray SB_OID_GOST_R3410_1994_DH;
extern PACKAGE Sbtypes::ByteArray SB_OID_GOST_R3411_1994_WITH_GOST_R3410_2001;
extern PACKAGE Sbtypes::ByteArray SB_OID_GOST_R3411_1994_WITH_GOST_R3410_1994;
extern PACKAGE Sbtypes::ByteArray SB_OID_GOST_R3411_1994;
extern PACKAGE Sbtypes::ByteArray SB_OID_GOST_R3411_1994_HMAC;
extern PACKAGE Sbtypes::ByteArray SB_OID_GOST_28147_1989_PARAM_CP_TEST;
extern PACKAGE Sbtypes::ByteArray SB_OID_GOST_28147_1989_PARAM_CP_A;
extern PACKAGE Sbtypes::ByteArray SB_OID_GOST_28147_1989_PARAM_CP_B;
extern PACKAGE Sbtypes::ByteArray SB_OID_GOST_28147_1989_PARAM_CP_C;
extern PACKAGE Sbtypes::ByteArray SB_OID_GOST_28147_1989_PARAM_CP_D;
extern PACKAGE Sbtypes::ByteArray SB_OID_GOST_28147_1989_PARAM_CP_OSCAR_11;
extern PACKAGE Sbtypes::ByteArray SB_OID_GOST_28147_1989_PARAM_CP_OSCAR_10;
extern PACKAGE Sbtypes::ByteArray SB_OID_GOST_28147_1989_PARAM_CP_RIC_1;
extern PACKAGE Sbtypes::ByteArray SB_OID_GOST_R3411_1994_PARAM_CP_TEST;
extern PACKAGE Sbtypes::ByteArray SB_OID_GOST_R3411_1994_PARAM_CP;
extern PACKAGE Sbtypes::ByteArray SB_OID_GOST_R3410_1994_PARAM_CP_TEST;
extern PACKAGE Sbtypes::ByteArray SB_OID_GOST_R3410_1994_PARAM_CP_A;
extern PACKAGE Sbtypes::ByteArray SB_OID_GOST_R3410_1994_PARAM_CP_B;
extern PACKAGE Sbtypes::ByteArray SB_OID_GOST_R3410_1994_PARAM_CP_C;
extern PACKAGE Sbtypes::ByteArray SB_OID_GOST_R3410_1994_PARAM_CP_D;
extern PACKAGE Sbtypes::ByteArray SB_OID_GOST_R3410_1994_PARAM_CP_XCHA;
extern PACKAGE Sbtypes::ByteArray SB_OID_GOST_R3410_1994_PARAM_CP_XCHB;
extern PACKAGE Sbtypes::ByteArray SB_OID_GOST_R3410_1994_PARAM_CP_XCHC;
extern PACKAGE Sbtypes::ByteArray SB_OID_FLD_CUSTOM;
extern PACKAGE Sbtypes::ByteArray SB_OID_FLD_TYPE_FP;
extern PACKAGE Sbtypes::ByteArray SB_OID_FLD_TYPE_F2M;
extern PACKAGE Sbtypes::ByteArray SB_OID_FLD_BASIS_N;
extern PACKAGE Sbtypes::ByteArray SB_OID_FLD_BASIS_T;
extern PACKAGE Sbtypes::ByteArray SB_OID_FLD_BASIS_P;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_KEY;
extern PACKAGE Sbtypes::ByteArray SB_OID_ECDH;
extern PACKAGE Sbtypes::ByteArray SB_OID_ECMQV;
extern PACKAGE Sbtypes::ByteArray SB_OID_ECDSA_SHA1;
extern PACKAGE Sbtypes::ByteArray SB_OID_ECDSA_RECOMMENDED;
extern PACKAGE Sbtypes::ByteArray SB_OID_ECDSA_SHA224;
extern PACKAGE Sbtypes::ByteArray SB_OID_ECDSA_SHA256;
extern PACKAGE Sbtypes::ByteArray SB_OID_ECDSA_SHA384;
extern PACKAGE Sbtypes::ByteArray SB_OID_ECDSA_SHA512;
extern PACKAGE Sbtypes::ByteArray SB_OID_ECDSA_SPECIFIED;
extern PACKAGE Sbtypes::ByteArray SB_OID_ECDSA_PLAIN_SHA1;
extern PACKAGE Sbtypes::ByteArray SB_OID_ECDSA_PLAIN_SHA224;
extern PACKAGE Sbtypes::ByteArray SB_OID_ECDSA_PLAIN_SHA256;
extern PACKAGE Sbtypes::ByteArray SB_OID_ECDSA_PLAIN_SHA384;
extern PACKAGE Sbtypes::ByteArray SB_OID_ECDSA_PLAIN_SHA512;
extern PACKAGE Sbtypes::ByteArray SB_OID_ECDSA_PLAIN_RIPEMD160;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_CUSTOM;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_C2PNB163V1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_C2PNB163V2;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_C2PNB163V3;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_C2PNB176W1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_C2TNB191V1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_C2TNB191V2;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_C2TNB191V3;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_C2ONB191V4;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_C2ONB191V5;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_C2PNB208W1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_C2TNB239V1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_C2TNB239V2;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_C2TNB239V3;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_C2ONB239V4;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_C2ONB239V5;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_C2PNB272W1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_C2PNB304W1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_C2TNB359V1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_C2PNB368W1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_C2TNB431R1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_PRIME192V1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_PRIME192V2;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_PRIME192V3;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_PRIME239V1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_PRIME239V2;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_PRIME239V3;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_PRIME256V1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECP112R1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECP112R2;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECP128R1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECP128R2;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECP160K1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECP160R1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECP160R2;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECP192K1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECP192R1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECP224K1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECP224R1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECP256K1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECP256R1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECP384R1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECP521R1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECT113R1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECT113R2;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECT131R1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECT131R2;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECT163K1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECT163R1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECT163R2;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECT193R1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECT193R2;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECT233K1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECT233R1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECT239K1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECT283K1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECT283R1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECT409K1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECT409R1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECT571K1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_SECT571R1;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_GOST_CP_TEST;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_GOST_CP_A;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_GOST_CP_B;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_GOST_CP_C;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_GOST_CP_XCHA;
extern PACKAGE Sbtypes::ByteArray SB_OID_EC_GOST_CP_XCHB;
extern PACKAGE Sbtypes::ByteArray SB_OID_ELDOSCORP_BASE;
extern PACKAGE Sbtypes::ByteArray SB_OID_ELDOS_PKI;
extern PACKAGE Sbtypes::ByteArray SB_OID_ELDOS_ALGS;
extern PACKAGE Sbtypes::ByteArray SB_OID_ELDOS_DATASTORAGE;
extern PACKAGE Sbtypes::ByteArray SB_OID_ELDOS_ALGS_NULL;
extern PACKAGE Sbtypes::ByteArray SB_OID_ELDOS_ALGS_PKEY;
extern PACKAGE Sbtypes::ByteArray SB_OID_ELDOS_ALGS_SKEY;
extern PACKAGE Sbtypes::ByteArray SB_OID_ELDOS_ALGS_DGST;
extern PACKAGE Sbtypes::ByteArray SB_OID_ELDOS_ALGS_HMAC;
extern PACKAGE Sbtypes::ByteArray SB_OID_ELDOS_ALGS_COMPR;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_COMMON_NAME;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_SURNAME;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_COUNTRY;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_LOCALITY;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_STATE_OR_PROVINCE;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_ORGANIZATION;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_ORGANIZATION_UNIT;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_TITLE;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_NAME;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_GIVEN_NAME;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_INITIALS;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_GENERATION_QUALIFIER;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_DN_QUALIFIER;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_EMAIL;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_STREET_ADDRESS;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_POSTAL_ADDRESS;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_POSTAL_CODE;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_POST_OFFICE_BOX;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_PHYSICAL_DELIVERY_OFFICE_NAME;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_TELEPHONE_NUMBER;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_TELEX_NUMBER;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_TELEX_TERMINAL_ID;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_FACIMILE_PHONE_NUMBER;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_X12_ADDRESS;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_INTERNATIONAL_ISDN_NUMBER;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_REGISTERED_ADDRESS;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_DESTINATION_INDICATOR;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_PREFERRED_DELIVERY_METHOD;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_PRESENTATION_ADDRESS;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_SUPPORTED_APPLICATION_CONTEXT;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_MEMBER;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_OWNER;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_ROLE_OCCUPENT;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_SEE_ALSO;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_USER_PASSWORD;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_USER_CERTIFICATE;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_CA_CERTIFICATE;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_AUTHORITY_REVOCATION_LIST;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_CERTIFICATE_REVOCATION_LIST;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_CERTIFICATE_PAIR;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_UNIQUE_IDENTIFIER;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_ENHANCED_SEARCH_GUIDE;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_OBJECT_CLASS;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_ALIASED_ENTRY_NAME;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_KNOWLEDGE_INFORMATION;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_SERIAL_NUMBER;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_DESCRIPTION;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_SEARCH_GUIDE;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_BUSINESS_CATEGORY;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_PROTOCOL_INFORMATION;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_DISTINGUISHED_NAME;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_UNIQUE_MEMBER;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_HOUSE_IDENTIFIER;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_SUPPORTED_ALGORITHMS;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_DELTA_REVOCATION_LIST;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_ATTRIBUTE_CERTIFICATE;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_PSEUDONYM;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_PERMANENT_IDENTIFIER;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_USER_ID;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_DOMAIN_COMPONENT;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_CA_OCSP;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_CA_ISSUER;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_RSAENCRYPTION;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_RSAOAEP;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_RSAPSS;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_DSA;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_DH;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_DSA_SHA1;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_DSA_SHA224;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_DSA_SHA256;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_MD2_RSAENCRYPTION;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_MD5_RSAENCRYPTION;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_SHA1_RSAENCRYPTION;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_SHA224_RSAENCRYPTION;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_SHA256_RSAENCRYPTION;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_SHA384_RSAENCRYPTION;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_SHA512_RSAENCRYPTION;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_ECDSA_SHA1;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_ECDSA_RECOMMENDED;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_ECDSA_SHA224;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_ECDSA_SHA256;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_ECDSA_SHA384;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_ECDSA_SHA512;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_ECDSA_SPECIFIED;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_ECDSA_PLAIN_SHA1;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_ECDSA_PLAIN_SHA224;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_ECDSA_PLAIN_SHA256;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_ECDSA_PLAIN_SHA384;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_ECDSA_PLAIN_SHA512;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_ECDSA_PLAIN_RIPEMD160;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_GOST_R3410_1994;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_GOST_R3410_2001;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_GOST_R3411_WITH_GOST3410_1994;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_GOST_R3411_WITH_GOST3410_2001;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_SHA1_RSA;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_SHA1_DSA;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_SHA1;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_MD2;
extern PACKAGE Sbtypes::ByteArray SB_CERT_OID_MD5;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_PKI_DATA;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_PKI_RESPONSE;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_STATUS_INFO;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_IDENTIFICATION;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_IDENTITY_PROOF;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_DATA_RETURN;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_TRANSACTION_ID;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_SENDER_NONCE;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_RECIPIENT_NONCE;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_ADD_EXTENSIONS;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_ENCRYPTED_POP;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_DECRYPTED_POP;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_LRA_POP_WITNESS;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_GET_CERT;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_GET_CRL;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_REVOKE_REQUEST;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_REG_INFO;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_RESPONSE_INFO;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_QUERY_PENDING;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_POP_LINK_RANDOM;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_POP_LINK_WITNESS;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_POP_LINK_WITNESS_V2;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_CONFIRM_CERT_ACCEPTANCE;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_STATUS_INFO_V2;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_TRUSTED_ANCHORS;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_AUTH_DATA;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_BATCH_REQUESTS;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_BATCH_RESPONSES;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_PUBLISH_CERT;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_MOD_CERT_TEMPLATE;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_CONTROL_PROCESSED;
extern PACKAGE Sbtypes::ByteArray SB_CMC_OID_IDENTITY_PROOF_V2;
static const Word SB_ALGORITHM_CNT_BASE = 0x7000;
static const short SB_ALGORITHM_CNT_RC4 = 28673;
static const short SB_ALGORITHM_CNT_DES = 28674;
static const short SB_ALGORITHM_CNT_3DES = 28675;
static const short SB_ALGORITHM_CNT_RC2 = 28676;
static const short SB_ALGORITHM_CNT_AES128 = 28677;
static const short SB_ALGORITHM_CNT_AES192 = 28678;
static const short SB_ALGORITHM_CNT_AES256 = 28679;
static const short SB_ALGORITHM_CNT_IDENTITY = 28682;
static const short SB_ALGORITHM_CNT_BLOWFISH = 28688;
static const short SB_ALGORITHM_CNT_TWOFISH = 28689;
static const short SB_ALGORITHM_CNT_CAMELLIA = 28690;
static const short SB_ALGORITHM_CNT_CAST128 = 28691;
static const short SB_ALGORITHM_CNT_IDEA = 28692;
static const short SB_ALGORITHM_CNT_SERPENT = 28693;
static const short SB_ALGORITHM_CNT_TWOFISH128 = 28694;
static const short SB_ALGORITHM_CNT_TWOFISH192 = 28695;
static const short SB_ALGORITHM_CNT_TWOFISH256 = 28696;
static const short SB_ALGORITHM_CNT_CAMELLIA128 = 28697;
static const short SB_ALGORITHM_CNT_CAMELLIA192 = 28698;
static const short SB_ALGORITHM_CNT_CAMELLIA256 = 28699;
static const short SB_ALGORITHM_CNT_SERPENT128 = 28700;
static const short SB_ALGORITHM_CNT_SERPENT192 = 28701;
static const short SB_ALGORITHM_CNT_SERPENT256 = 28702;
static const short SB_ALGORITHM_CNT_SEED = 28704;
static const short SB_ALGORITHM_CNT_RABBIT = 28705;
static const short SB_ALGORITHM_CNT_SYMMETRIC = 28706;
static const short SB_ALGORITHM_CNT_GOST_28147_1989 = 28707;
static const Word SB_ALGORITHM_PK_BASE = 0x7400;
static const short SB_ALGORITHM_PK_RSA = 29697;
static const short SB_ALGORITHM_PK_DSA = 29698;
static const short SB_ALGORITHM_PK_ELGAMAL = 29699;
static const short SB_ALGORITHM_PK_GOST_R3410_1994 = 29700;
static const short SB_ALGORITHM_PK_EC = 29701;
static const short SB_ALGORITHM_PK_ECDSA = 29702;
static const short SB_ALGORITHM_PK_DH = 29703;
static const short SB_ALGORITHM_PK_SRP = 29704;
static const short SB_ALGORITHM_PK_ECDH = 29705;
static const short SB_ALGORITHM_PK_GOST_R3410_2001 = 29706;
static const Word SB_ALGORITHM_DGST_BASE = 0x7100;
static const short SB_ALGORITHM_DGST_SHA1 = 28929;
static const short SB_ALGORITHM_DGST_MD5 = 28930;
static const short SB_ALGORITHM_DGST_MD2 = 28931;
static const short SB_ALGORITHM_DGST_SHA256 = 28932;
static const short SB_ALGORITHM_DGST_SHA384 = 28933;
static const short SB_ALGORITHM_DGST_SHA512 = 28934;
static const short SB_ALGORITHM_DGST_SHA224 = 28935;
static const short SB_ALGORITHM_DGST_MD4 = 28936;
static const short SB_ALGORITHM_DGST_RIPEMD160 = 28937;
static const short SB_ALGORITHM_DGST_CRC32 = 28938;
static const short SB_ALGORITHM_DGST_SSL3 = 28939;
static const short SB_ALGORITHM_DGST_GOST_R3411_1994 = 28940;
static const short SB_ALGORITHM_DGST_WHIRLPOOL = 28941;
static const Word SB_ALGORITHM_PBE_BASE = 0x7200;
static const short SB_ALGORITHM_PBE_SHA1_RC4_128 = 29185;
static const short SB_ALGORITHM_PBE_SHA1_RC4_40 = 29186;
static const short SB_ALGORITHM_PBE_SHA1_3DES = 29187;
static const short SB_ALGORITHM_PBE_SHA1_RC2_128 = 29188;
static const short SB_ALGORITHM_PBE_SHA1_RC2_40 = 29189;
static const short SB_ALGORITHM_P5_PBE_MD2_DES = 29217;
static const short SB_ALGORITHM_P5_PBE_MD2_RC2 = 29218;
static const short SB_ALGORITHM_P5_PBE_MD5_DES = 29219;
static const short SB_ALGORITHM_P5_PBE_MD5_RC2 = 29220;
static const short SB_ALGORITHM_P5_PBE_SHA1_DES = 29221;
static const short SB_ALGORITHM_P5_PBE_SHA1_RC2 = 29222;
static const short SB_ALGORITHM_P5_PBES1 = 29249;
static const short SB_ALGORITHM_P5_PBES2 = 29250;
static const short SB_ALGORITHM_P5_PBKDF1 = 29265;
static const short SB_ALGORITHM_P5_PBKDF2 = 29266;
static const short SB_ALGORITHM_P5_PBMAC1 = 29281;
static const Word SB_ALGORITHM_MAC_BASE = 0x7300;
static const short SB_ALGORITHM_MAC_HMACSHA1 = 29441;
static const short SB_ALGORITHM_MAC_HMACSHA224 = 29442;
static const short SB_ALGORITHM_MAC_HMACSHA256 = 29443;
static const short SB_ALGORITHM_MAC_HMACSHA384 = 29444;
static const short SB_ALGORITHM_MAC_HMACSHA512 = 29445;
static const short SB_ALGORITHM_MAC_HMACMD5 = 29446;
static const short SB_ALGORITHM_MAC_HMACRIPEMD = 29447;
static const short SB_ALGORITHM_HMAC = 29448;
static const short SB_ALGORITHM_UMAC32 = 29456;
static const short SB_ALGORITHM_UMAC64 = 29457;
static const short SB_ALGORITHM_UMAC96 = 29458;
static const short SB_ALGORITHM_UMAC128 = 29459;
static const short SB_ALGORITHM_MAC_GOST_28147_1989 = 29460;
static const short SB_ALGORITHM_HMAC_GOST_R3411_1994 = 29461;
static const short SB_ALGORITHM_UNKNOWN = 32767;
static const Word SB_EC_FLD_TYPE_BASE = 0x6000;
static const short SB_EC_FLD_TYPE_UNKNOWN = 24576;
static const short SB_EC_FLD_TYPE_FP = 24577;
static const short SB_EC_FLD_TYPE_F2MP = 24578;
static const short SB_EC_FLD_TYPE_F2MN = 24579;
static const Word SB_EC_FLD_BASE = 0x6100;
static const short SB_EC_FLD_FIRST = 24832;
static const short SB_EC_FLD_CUSTOM = 24832;
static const short SB_EC_FLD_NIST_P192S = 24833;
static const short SB_EC_FLD_NIST_P224S = 24834;
static const short SB_EC_FLD_NIST_P256S = 24835;
static const short SB_EC_FLD_NIST_P384 = 24836;
static const short SB_EC_FLD_NIST_P521 = 24837;
static const short SB_EC_FLD_NIST_B163 = 24838;
static const short SB_EC_FLD_NIST_B233 = 24839;
static const short SB_EC_FLD_NIST_B283 = 24840;
static const short SB_EC_FLD_NIST_B409 = 24841;
static const short SB_EC_FLD_NIST_B571 = 24842;
static const short SB_EC_FLD_LAST = 24842;
static const ShortInt SB_ECDSA_WRAP_SHIFT = 0x0;
static const ShortInt SB_ECDSA_WRAP_MOD_N = 0x1;
static const Word SB_EC_BASE = 0x6200;
static const short SB_EC_FIRST = 25088;
static const short SB_EC_CUSTOM = 25088;
static const short SB_EC_SECP112R1 = 25089;
static const short SB_EC_SECP112R2 = 25090;
static const short SB_EC_SECP128R1 = 25091;
static const short SB_EC_SECP128R2 = 25092;
static const short SB_EC_SECP160K1 = 25093;
static const short SB_EC_SECP160R1 = 25094;
static const short SB_EC_SECP160R2 = 25095;
static const short SB_EC_SECP192K1 = 25096;
static const short SB_EC_SECP192R1 = 25097;
static const short SB_EC_SECP224K1 = 25098;
static const short SB_EC_SECP224R1 = 25099;
static const short SB_EC_SECP256K1 = 25100;
static const short SB_EC_SECP256R1 = 25101;
static const short SB_EC_SECP384R1 = 25102;
static const short SB_EC_SECP521R1 = 25103;
static const short SB_EC_SECT113R1 = 25104;
static const short SB_EC_SECT113R2 = 25105;
static const short SB_EC_SECT131R1 = 25106;
static const short SB_EC_SECT131R2 = 25107;
static const short SB_EC_SECT163K1 = 25108;
static const short SB_EC_SECT163R1 = 25109;
static const short SB_EC_SECT163R2 = 25110;
static const short SB_EC_SECT193R1 = 25111;
static const short SB_EC_SECT193R2 = 25112;
static const short SB_EC_SECT233K1 = 25113;
static const short SB_EC_SECT233R1 = 25114;
static const short SB_EC_SECT239K1 = 25115;
static const short SB_EC_SECT283K1 = 25116;
static const short SB_EC_SECT283R1 = 25117;
static const short SB_EC_SECT409K1 = 25118;
static const short SB_EC_SECT409R1 = 25119;
static const short SB_EC_SECT571K1 = 25120;
static const short SB_EC_SECT571R1 = 25121;
static const short SB_EC_PRIME192V1 = 25097;
static const short SB_EC_PRIME192V2 = 25122;
static const short SB_EC_PRIME192V3 = 25123;
static const short SB_EC_PRIME239V1 = 25124;
static const short SB_EC_PRIME239V2 = 25125;
static const short SB_EC_PRIME239V3 = 25126;
static const short SB_EC_PRIME256V1 = 25101;
static const short SB_EC_C2PNB163V1 = 25127;
static const short SB_EC_C2PNB163V2 = 25128;
static const short SB_EC_C2PNB163V3 = 25129;
static const short SB_EC_C2PNB176W1 = 25130;
static const short SB_EC_C2TNB191V1 = 25131;
static const short SB_EC_C2TNB191V2 = 25132;
static const short SB_EC_C2TNB191V3 = 25133;
static const short SB_EC_C2ONB191V4 = 25134;
static const short SB_EC_C2ONB191V5 = 25135;
static const short SB_EC_C2PNB208W1 = 25136;
static const short SB_EC_C2TNB239V1 = 25137;
static const short SB_EC_C2TNB239V2 = 25138;
static const short SB_EC_C2TNB239V3 = 25139;
static const short SB_EC_C2ONB239V4 = 25140;
static const short SB_EC_C2ONB239V5 = 25141;
static const short SB_EC_C2PNB272W1 = 25142;
static const short SB_EC_C2PNB304W1 = 25143;
static const short SB_EC_C2TNB359V1 = 25144;
static const short SB_EC_C2PNB368W1 = 25145;
static const short SB_EC_C2TNB431R1 = 25146;
static const short SB_EC_NIST_P192 = 25097;
static const short SB_EC_NIST_P224 = 25099;
static const short SB_EC_NIST_P256 = 25101;
static const short SB_EC_NIST_P384 = 25102;
static const short SB_EC_NIST_P521 = 25103;
static const short SB_EC_NIST_B163 = 25110;
static const short SB_EC_NIST_B233 = 25114;
static const short SB_EC_NIST_B283 = 25117;
static const short SB_EC_NIST_B409 = 25119;
static const short SB_EC_NIST_B571 = 25121;
static const short SB_EC_NIST_K163 = 25108;
static const short SB_EC_NIST_K233 = 25113;
static const short SB_EC_NIST_K283 = 25116;
static const short SB_EC_NIST_K409 = 25118;
static const short SB_EC_NIST_K571 = 25120;
static const short SB_EC_GOST_CP_TEST = 25147;
static const short SB_EC_GOST_CP_A = 25148;
static const short SB_EC_GOST_CP_B = 25149;
static const short SB_EC_GOST_CP_C = 25150;
static const short SB_EC_GOST_CP_XCHA = 25151;
static const short SB_EC_GOST_CP_XCHB = 25152;
static const short SB_EC_LAST = 25152;
static const Word SB_GOST_PARAM_BASE = 0x6300;
static const short SB_GOST_PARAM_NONE = 25344;
static const short SB_GOST_PARAM_CUSTOM = 25345;
static const short SB_GOST_28147_1989_PARAM_CP_TEST = 25346;
static const short SB_GOST_28147_1989_PARAM_CP_A = 25347;
static const short SB_GOST_28147_1989_PARAM_CP_B = 25348;
static const short SB_GOST_28147_1989_PARAM_CP_C = 25349;
static const short SB_GOST_28147_1989_PARAM_CP_D = 25350;
static const short SB_GOST_28147_1989_PARAM_CP_OSCAR_11 = 25351;
static const short SB_GOST_28147_1989_PARAM_CP_OSCAR_10 = 25352;
static const short SB_GOST_28147_1989_PARAM_CP_RIC_1 = 25353;
static const short SB_GOST_R3411_1994_PARAM_CP_TEST = 25354;
static const short SB_GOST_R3411_1994_PARAM_CP = 25355;
static const short SB_GOST_R3410_1994_PARAM_CP_TEST = 25356;
static const short SB_GOST_R3410_1994_PARAM_CP_A = 25357;
static const short SB_GOST_R3410_1994_PARAM_CP_B = 25358;
static const short SB_GOST_R3410_1994_PARAM_CP_C = 25359;
static const short SB_GOST_R3410_1994_PARAM_CP_D = 25360;
static const short SB_GOST_R3410_1994_PARAM_CP_XCHA = 25361;
static const short SB_GOST_R3410_1994_PARAM_CP_XCHB = 25362;
static const short SB_GOST_R3410_1994_PARAM_CP_XCHC = 25363;
#define LowerAlphabet L"0123456789abcdef"
#define UpperAlphabet L"0123456789ABCDEF"
extern PACKAGE Sbtypes::ByteArray SpaceByteArray;
extern PACKAGE Sbtypes::ByteArray CommaByteArray;
extern PACKAGE Sbtypes::ByteArray SlashByteArray;
extern PACKAGE Sbtypes::ByteArray ColonByteArray;
extern PACKAGE Sbtypes::ByteArray EqualCharByteArray;
extern PACKAGE Sbtypes::ByteArray DashByteArray;
extern PACKAGE Sbtypes::ByteArray LFByteArray;
extern PACKAGE Sbtypes::ByteArray CRByteArray;
extern PACKAGE Sbtypes::ByteArray LFLFByteArray;
extern PACKAGE Sbtypes::ByteArray CRLFByteArray;
extern PACKAGE Sbtypes::ByteArray CRLFCRLFByteArray;
extern PACKAGE Sbtypes::ByteArray CRCRLFByteArray;
extern PACKAGE Sbtypes::ByteArray CRLFTABByteArray;
extern PACKAGE Sbtypes::ByteArray CRLFSPACEByteArray;
extern PACKAGE Sbtypes::ByteArray CRCRLFCRCRLFByteArray;
extern PACKAGE Sbtypes::ByteArray TwoDashesByteArray;
extern PACKAGE Sbtypes::ByteArray FiveDashesByteArray;
extern PACKAGE Sbtypes::ByteArray BeginLineByteArray;
extern PACKAGE Sbtypes::ByteArray LFEndLineByteArray;
extern PACKAGE Sbtypes::ByteArray UTF8BOMByteArray;
extern PACKAGE StaticArray<unsigned, 6> offsetsFromUTF8;
extern PACKAGE StaticArray<System::Byte, 7> firstByteMark;
extern PACKAGE int __fastcall GetPBEAlgorithmByOID(const Sbtypes::ByteArray OID);
extern PACKAGE Sbtypes::ByteArray __fastcall GetOIDByPBEAlgorithm(int Algorithm);
extern PACKAGE int __fastcall GetPKAlgorithmByOID(const Sbtypes::ByteArray OID);
extern PACKAGE Sbtypes::ByteArray __fastcall GetOIDByPKAlgorithm(int Algorithm);
extern PACKAGE int __fastcall GetSigAlgorithmByOID(const Sbtypes::ByteArray OID);
extern PACKAGE Sbtypes::ByteArray __fastcall GetOIDBySigAlgorithm(int Algorithm);
extern PACKAGE int __fastcall GetHashAlgorithmBySigAlgorithm(int Algorithm);
extern PACKAGE int __fastcall GetHMACAlgorithmByHashAlgorithm(int Algorithm);
extern PACKAGE int __fastcall GetHashAlgorithmByHMACAlgorithm(int Algorithm);
extern PACKAGE int __fastcall GetSigAlgorithmByHashAlgorithm(int BasePKAlg, int HashAlg);
extern PACKAGE int __fastcall GetKeyAlgorithmBySigAlgorithm(int SigAlg);
extern PACKAGE int __fastcall GetSigAlgorithmByKeyAlgorithm(int KeyAlg);
extern PACKAGE int __fastcall NormalizeAlgorithmConstant(int Value);
extern PACKAGE int __fastcall GetAlgorithmByOID(const Sbtypes::ByteArray OID, bool UseCryptoProvConstants = false);
extern PACKAGE System::UnicodeString __fastcall GetAlgorithmNameByAlgorithm(int Algorithm);
extern PACKAGE System::UnicodeString __fastcall GetAlgorithmNameByOID(const Sbtypes::ByteArray OID);
extern PACKAGE Sbtypes::ByteArray __fastcall GetOIDByAlgorithm(int Algorithm);
extern PACKAGE int __fastcall GetHashAlgorithmByOID(const Sbtypes::ByteArray OID);
extern PACKAGE Sbtypes::ByteArray __fastcall GetOIDByHashAlgorithm(int Algorithm);
extern PACKAGE bool __fastcall IsSymmetricKeyAlgorithm(int Algorithm);
extern PACKAGE bool __fastcall IsPublicKeyAlgorithm(int Algorithm);
extern PACKAGE bool __fastcall IsHashAlgorithm(int Algorithm);
extern PACKAGE bool __fastcall IsMACAlgorithm(int Algorithm);
extern PACKAGE int __fastcall MGF1AlgorithmByHash(int Value);
extern PACKAGE int __fastcall HashAlgorithmByMGF1(int Value);

}	/* namespace Sbconstants */
using namespace Sbconstants;
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// SbconstantsHPP
